#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN 1
#define NOMINMAX
#include <Windows.h>
#include "GL/gl.h"
#include "3p/opengl/glext.h"
#include "3p/opengl/wglext.h"

#define GLFUNCLIST \
  GLFUNCLIST_DO(PFNGLCREATESHADERPROC, glCreateShader) \
  GLFUNCLIST_DO(PFNGLSHADERSOURCEPROC, glShaderSource) \
  GLFUNCLIST_DO(PFNGLCOMPILESHADERPROC, glCompileShader) \
  GLFUNCLIST_DO(PFNGLGETSHADERIVPROC, glGetShaderiv) \
  GLFUNCLIST_DO(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog) \
  GLFUNCLIST_DO(PFNGLDELETESHADERPROC, glDeleteShader) \
  GLFUNCLIST_DO(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers) \
  GLFUNCLIST_DO(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray) \
  GLFUNCLIST_DO(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer) \
  GLFUNCLIST_DO(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer) \
  GLFUNCLIST_DO(PFNGLFRAMEBUFFERTEXTURE2DPROC, glFramebufferTexture2D) \
  GLFUNCLIST_DO(PFNGLCHECKFRAMEBUFFERSTATUSPROC, glCheckFramebufferStatus) \
  GLFUNCLIST_DO(PFNGLUSEPROGRAMPROC, glUseProgram) \
  GLFUNCLIST_DO(PFNGLUNIFORM1FPROC, glUniform1f) \
  GLFUNCLIST_DO(PFNGLUNIFORM2FPROC, glUniform2f) \
  GLFUNCLIST_DO(PFNGLUNIFORM1IPROC, glUniform1i) \
  GLFUNCLIST_DO(PFNGLCREATEPROGRAMPROC, glCreateProgram) \
  GLFUNCLIST_DO(PFNGLATTACHSHADERPROC, glAttachShader) \
  GLFUNCLIST_DO(PFNGLBINDATTRIBLOCATIONPROC, glBindAttribLocation) \
  GLFUNCLIST_DO(PFNGLLINKPROGRAMPROC, glLinkProgram) \
  GLFUNCLIST_DO(PFNGLGETPROGRAMIVPROC, glGetProgramiv) \
  GLFUNCLIST_DO(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog) \
  GLFUNCLIST_DO(PFNGLDELETEPROGRAMPROC, glDeleteProgram) \
  GLFUNCLIST_DO(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation)

#define WGLFUNCLSIT \
  GLFUNCLIST_DO(PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB) \
  GLFUNCLIST_DO(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB) \
  GLFUNCLIST_DO(PFNWGLSWAPINTERVALEXTPROC, wglSwapIntervalEXT)

#define GLFUNCLIST_DO(T,N) extern T N;
GLFUNCLIST
WGLFUNCLSIT
#undef GLFUNCLIST_DO

#elif defined(__linux__)
#define GL_GLEXT_PROTOTYPES 1
#include <GL/gl.h>
#include "3p/opengl/glext.h"
#else
#error unsupported platform
#endif